#include "StudioTape.h"
#include <juce_audio_formats/juce_audio_formats.h>
#include <juce_events/juce_events.h>
#include <iostream>
#include <fstream>
#include <chrono>
using namespace tide::room;
void check(bool v,const char* s){if(!v)throw std::runtime_error(s);}
void wav(const juce::File& path,const juce::AudioBuffer<float>& b,double sr){juce::WavAudioFormat f;auto stream=path.createOutputStream();check(stream!=nullptr,"stream");stream->setPosition(0);stream->truncate();std::unique_ptr<juce::AudioFormatWriter>w(f.createWriterFor(stream.release(),sr,2,32,{},0));check(w&&w->writeFromAudioSampleBuffer(b,0,b.getNumSamples()),"wav");}
juce::AudioBuffer<float> run(const juce::AudioBuffer<float>& x,double sr,StudioSettings s,int block=512,int order=0){StudioTape t;t.setSettings(s);t.setReferenceOrder(order);t.prepare(sr,512);juce::AudioBuffer<float> out;out.makeCopyOf(x);const auto start=std::chrono::steady_clock::now();for(int o=0;o<out.getNumSamples();o+=block){juce::AudioBuffer<float>b(out.getArrayOfWritePointers(),2,o,std::min(block,out.getNumSamples()-o));t.process(b);}const double sec=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();check(t.guardCount()==0,"guards");for(int c=0;c<2;++c)for(int i=0;i<out.getNumSamples();++i)check(std::isfinite(out.getSample(c,i)),"finite");std::cout<<"render sr="<<sr<<" q="<<(order?1<<order:1<<(s.quality+2))<<" drive="<<s.drive<<" cream="<<s.cream<<" cpu="<<sec/(out.getNumSamples()/sr)<<" peak="<<out.getMagnitude(0,out.getNumSamples())<<"\n";return out;}
int main(int argc,char**argv){juce::ScopedJuceInitialiser_GUI gui;try{check(argc>=3,"--probes/--render/--unit OUT [INPUT]");auto folder=juce::File::getCurrentWorkingDirectory().getChildFile(argv[2]);folder.createDirectory();juce::String mode(argv[1]);StudioSettings s;s.noise=0;s.motion=0;s.trim=0;s.drive=0;s.cream=0;
 if(mode=="--calibration"){
  s.quality=2;const double sr=48000;for(int hz:{1000,10000,16000})for(double db:{-30.,-18.,-17.96928863,-14.,-9.,-8.720943825,-4.70302463,6.,18.}){juce::AudioBuffer<float>x(2,48000);for(int i=0;i<48000;++i)for(int c=0;c<2;++c)x.setSample(c,i,(float)(std::pow(10.,db/20.)*std::sin(juce::MathConstants<double>::twoPi*hz*i/sr)));auto y=run(x,sr,s);wav(folder.getChildFile("cal-"+juce::String(hz)+"-"+juce::String(db,4)+".wav"),y,sr);}
  for(int kind=0;kind<5;++kind){s=StudioSettings{};s.drive=0;s.trim=0;s.cream=0;s.noise=kind==0?1:0;s.motion=kind==1?1:0;const int len=kind<2?48000*20:48000*3;juce::AudioBuffer<float>x(2,len);x.clear();for(int i=0;i<len;++i){float a=kind==0?0:kind==1?.1f*(float)std::sin(juce::MathConstants<double>::twoPi*3150*i/sr):kind==2?(i==24000?.1f:0):kind==3?((i>=24000&&i<36000)?.1f:0):.15f*(float)std::sin(juce::MathConstants<double>::twoPi*199*i/sr)*(i>=24000&&i<48000?1:0);for(int c=0;c<2;++c)x.setSample(c,i,a);}auto y=run(x,sr,s);wav(folder.getChildFile("behaviour-"+juce::String(kind)+".wav"),y,sr);}
 }else if(mode=="--probes"){
  const double sr=48000;for(int q:{1})for(int hz:{100,1000,10000})for(int db:{-30,-18,-12,-6,0,6,12}){juce::AudioBuffer<float>x(2,48000);for(int i=0;i<x.getNumSamples();++i)for(int c=0;c<2;++c)x.setSample(c,i,(float)(std::pow(10.,db/20.)*std::sin(juce::MathConstants<double>::twoPi*hz*i/sr)));s.quality=q;auto y=run(x,sr,s);wav(folder.getChildFile("tone-"+juce::String(hz)+"-"+juce::String(db)+".wav"),y,sr);}
  for(double rate:{44100.,48000.,96000.})for(int q=0;q<5;++q){juce::AudioBuffer<float>x(2,(int)rate*2);for(int i=0;i<x.getNumSamples();++i){double a=juce::MathConstants<double>::twoPi*i/rate;x.setSample(0,i,(float)(.3*std::sin(7001*a)+.07*std::sin(11003*a)));x.setSample(1,i,(float)(.5*std::sin(199*a)+.07*std::sin(6073*a)));}s.quality=std::min(2,q);s.drive=24;s.cream=1;auto y=run(x,rate,s,512,q>2?q+2:0);wav(folder.getChildFile("alias-"+juce::String((int)rate)+"-"+juce::String(1<<(q+2))+".wav"),y,rate);}
 }else if(mode=="--softness"){
  const double sr=48000;for(int level=0;level<2;++level)for(int cream=0;cream<2;++cream){s.drive=18;s.cream=cream?3:0;s.quality=2;juce::AudioBuffer<float>x(2,96000);for(int i=0;i<96000;++i){double a=juce::MathConstants<double>::twoPi*i/sr;x.setSample(0,i,(float)((level?.5:.0001)*std::sin(199*a)));x.setSample(1,i,(float)((level?.3:.0001)*(std::sin(199*a)+.2*std::sin(6073*a))));}auto y=run(x,sr,s);wav(folder.getChildFile("soft-"+juce::String(level)+"-"+juce::String(cream)+".wav"),y,sr);}
 }else if(mode=="--alias"){
  for(double sr:{44100.,48000.,96000.})for(int q=0;q<3;++q)for(int hz:{997,6073,11003,17003}){s.drive=30;s.cream=3;s.quality=q;juce::AudioBuffer<float>x(2,(int)sr*2);for(int i=0;i<x.getNumSamples();++i)for(int c=0;c<2;++c)x.setSample(c,i,(float)(.5*std::sin(juce::MathConstants<double>::twoPi*hz*i/sr)));auto y=run(x,sr,s);wav(folder.getChildFile(juce::String((int)sr)+"-"+juce::String(1<<(q+2))+"-"+juce::String(hz)+".wav"),y,sr);}
 }else if(mode=="--render"||mode=="--reference"){
  check(argc>=4,"input path");juce::AudioFormatManager fmt;fmt.registerBasicFormats();std::unique_ptr<juce::AudioFormatReader>r(fmt.createReaderFor(juce::File::getCurrentWorkingDirectory().getChildFile(argv[3])));check(r!=nullptr,"reader");juce::AudioBuffer<float>x(2,(int)r->lengthInSamples+1024);x.clear();r->read(&x,0,(int)r->lengthInSamples,0,true,true);
  for(int variant=0;variant<(mode=="--reference"?1:5);++variant){s.drive=variant==0?0:variant==3?27:18;s.cream=variant==0?0:variant==2?3:variant==3?2.2f:1;s.bias=variant==3?.2f:0;s.motion=variant==4?0:variant==3?1.8f:1;s.noise=variant==4?0:variant==0?1:variant==3?.25f:.15f;s.trim=0;s.quality=2;auto y=run(x,r->sampleRate,s);juce::AudioBuffer<float>aligned(y.getArrayOfWritePointers(),2,768,(int)r->lengthInSamples);wav(folder.getChildFile("studio-"+juce::String(variant)+".wav"),aligned,r->sampleRate);}
 }else if(mode=="--unit"){
  for(double sr:{44100.,48000.,96000.})for(int q=0;q<3;++q){s.quality=q;s.drive=24;s.cream=3;s.noise=0;s.motion=1;juce::AudioBuffer<float>x(2,24000);for(int i=0;i<x.getNumSamples();++i){float v=.25f*(float)std::sin(i*.12)+.04f*(float)std::sin(i*1.42);x.setSample(0,i,v);x.setSample(1,i,v);}auto a=run(x,sr,s,512),b=run(x,sr,s,127);for(int i=0;i<x.getNumSamples();++i){check(a.getSample(0,i)==a.getSample(1,i),"mono");check(a.getSample(0,i)==b.getSample(0,i),"partition");}x.clear();a=run(x,sr,s);check(a.getMagnitude(0,a.getNumSamples())==0,"silence");std::cout<<"PASS mono, block partition, silence "<<sr<<" "<<q<<"\n";}
 }else check(false,"mode");return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
