#pragma once
// Included only by the offline check executable.
void studioIntegrationChecks(const juce::File& out){
 using namespace tide::room;
 RoomProcessor p(false);p.set("tapeModel",2);p.set("studioDrive",22.7f);p.set("studioCream",2.42f);p.set("studioBias",-.4f);p.set("studioMotion",2.1f);p.set("studioNoise",.23f);p.set("studioTrim",3.1f);p.set("studioQuality",2);juce::MemoryBlock state;p.getStateInformation(state);p.set("tapeModel",0);p.set("studioDrive",0);p.setStateInformation(state.getData(),(int)state.getSize());check(p.get("tapeModel")==2&&std::abs(p.get("studioDrive")-22.7)<.01&&p.get("studioQuality")==2&&std::abs(p.get("studioCream")-2.42)<.01,"Studio state recall");
 auto tree=p.parameters.copyState();for(const auto* id:{"studioDrive","studioCream","studioBias","studioMotion","studioNoise","studioTrim","studioQuality"})tree.removeChild(tree.getChildWithProperty("id",id),nullptr);tree.getChildWithProperty("id","tapeModel").setProperty("value",1,nullptr);auto xml=tree.createXml();juce::AudioProcessor::copyXmlToBinary(*xml,state);p.setStateInformation(state.getData(),(int)state.getSize());check(p.get("tapeModel")==1&&p.get("studioDrive")==18,"Old scene changed model");
 std::cout<<"PASS Studio state and old scene migration\n";
 for(double sr:{44100.,48000.,96000.}){
  RoomTape rack;TapeSettings legacy;legacy.enabled=false;SpatialSettings spatial;StudioSettings studio;studio.noise=0;studio.motion=0;rack.setSettings(legacy,spatial,studio,2);rack.prepare(sr,512);juce::AudioBuffer<float> x(2,8192);std::vector<float> reference(8192);for(int i=0;i<8192;++i){reference[(size_t)i]=(float)(.1*std::sin(i*.11));for(int c=0;c<2;++c)x.setSample(c,i,reference[(size_t)i]);}rack.process(x);for(int i=0;i<8192;++i)check(x.getSample(0,i)==(i<768?0:reference[(size_t)i-768]),"Studio rack bypass latency");
 }
 std::cout<<"PASS Studio bit-exact bypass at 44.1/48/96 kHz\n";
 RoomTape rack;TapeSettings old;SpatialSettings spatial;StudioSettings studio;studio.noise=0;studio.motion=1;old.enabled=true;rack.setSettings(old,spatial,studio,2);rack.prepare(48000,512);juce::AudioBuffer<float> sequence(2,48000*8);float previous=0;double step=0,energy=0;int part=-1;
 for(int o=0;o<sequence.getNumSamples();o+=128){int segment=o/24000;if(segment!=part){part=segment;old.enabled=segment!=3&&segment!=10;old.mix=segment==12?.4f:1;studio.quality=segment%3;studio.drive=segment%2?30:8;studio.cream=segment%2?3:0;studio.motion=segment%2?3:0;studio.bias=segment%2?1:-1;rack.setSettings(old,spatial,studio,segment==6?1:segment==7?0:2);}
  const int n=std::min(128,sequence.getNumSamples()-o);juce::AudioBuffer<float>b(sequence.getArrayOfWritePointers(),2,o,n);for(int i=0;i<n;++i)for(int c=0;c<2;++c)b.setSample(c,i,(float)(.1*std::sin(juce::MathConstants<double>::twoPi*220*(o+i)/48000)));rack.process(b);for(int i=0;i<n;++i){float v=b.getSample(0,i);check(std::isfinite(v),"Studio transition finite");step=std::max(step,(double)std::abs(v-previous));energy+=v*v;previous=v;}}
 check(rack.guardCount()==0&&step<.01&&energy>1,"Studio transitions/clicks/guards");std::cout<<"PASS all model, power, quality and control transitions: peak step="<<step<<"\n";
 juce::WavAudioFormat fmt;auto stream=out.getChildFile("studio-transitions.wav").createOutputStream();stream->setPosition(0);stream->truncate();std::unique_ptr<juce::AudioFormatWriter>w(fmt.createWriterFor(stream.release(),48000,2,32,{},0));check(w&&w->writeFromAudioSampleBuffer(sequence,0,sequence.getNumSamples()),"Transition WAV");
 p.set("tapeModel",2);p.set("tapeOn",1);p.setRateAndBufferSizeDetails(48000,1024);p.prepareToPlay(48000,1024);check(p.getLatencySamples()==960,"Studio app reported latency");std::unique_ptr<juce::AudioProcessorEditor>editor(p.createEditor());auto pic=static_cast<RoomEditor*>(editor.get())->tapePanelSnapshot();juce::PNGImageFormat png;auto image=out.getChildFile("studio-controls.png").createOutputStream();png.writeImageToStream(pic,*image);std::cout<<"PASS Studio UI and latency\n";
}
